CREATE TABLE IF NOT EXISTS client
(
    id                 INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    client_status_call INT,
    date_call          DATE,
    duration           DOUBLE PRECISION,
    number             VARCHAR
);

INSERT INTO client(id, client_status_call, date_call, duration, number)
VALUES (1, 1, '2024-02-12', 3.24, '+7(918)548-00-11'),
       (2, 0, '2024-02-13', 2.34, '+7(918)548-00-11'),
       (3, 1, '2024-02-14', 4.24, '+7(918)548-00-11'),
       (4, 0, '2024-02-15', 3.54, '+7(918)548-00-11'),
       (5, 1, '2024-02-11', 3.24, '+7(918)548-00-11'),
       (6, 0, '2024-02-19', 5.21, '+7(918)548-00-11'),
       (7, 1, '2024-02-14', 1.39, '+7(918)548-00-11'),
       (8, 0, '2024-02-13', 0.24, '+7(918)548-00-11');