server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      retry:
        initial-interval: 2000
        max-attempts: 10
      server:
        git:
          uri: https://github.com/honeymoneyes/report-forge-configs
          default-label: master
          search-paths: "{application}"
      fail-fast: false
