networks:
  app-tool:
    driver: bridge

services:
  config-service:
    container_name: config-service
    build:
      context: spring-cloud-config
      dockerfile: Dockerfile
    depends_on:
      - kafka
    restart: always
    ports:
      - 8888:8888
    networks:
      - app-tool

  eureka:
    container_name: eureka-server
    build:
      context: eureka-server
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - kafka
      - config-service
    ports:
      - 2000:2000
    networks:
      - app-tool

  gateway:
    container_name: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - config-service
      - master-service
      - worker-service
      - client-service
      - eureka
    networks:
      - app-tool

  master-service:
    container_name: master-service
    build:
      context: master-service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - kafka
      - eureka
      - config-service
      - master-service-db
      - master-service-db-adminer
    networks:
      - app-tool

  worker-service:
    container_name: worker-service
    build:
      context: worker-service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - kafka
      - eureka
      - config-service
      - worker-service-db
      - worker-service-db-adminer
    networks:
      - app-tool

  client-service:
    container_name: client-service
    build:
      context: client-service
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - kafka
      - eureka
      - config-service
      - client-service-db
      - client-service-db-adminer
    networks:
      - app-tool

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
      - 22181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-tool

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092, PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    depends_on:
      - zookeeper
    networks:
      - app-tool

  master-service-db:
    container_name: master-service-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=alex
      - POSTGRES_DB=reports
    ports:
      - 5434:5432
    networks:
      - app-tool

  worker-service-db:
    container_name: worker-service-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=alex
      - POSTGRES_DB=reports
    ports:
      - 5433:5432
    networks:
      - app-tool

  client-service-db:
    container_name: client-service-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=alex
      - POSTGRES_DB=clients
    ports:
      - 5432:5432
    networks:
      - app-tool

  master-service-db-adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
    depends_on:
      - master-service-db
    networks:
      - app-tool

  worker-service-db-adminer:
    image: adminer
    restart: always
    ports:
      - 8084:8080
    depends_on:
      - worker-service-db
    networks:
      - app-tool

  client-service-db-adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
    depends_on:
      - client-service-db
    networks:
      - app-tool

  minio:
    container_name: minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    networks:
      - app-tool

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - app-tool
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc rm -r --force myminio/reports;
      /usr/bin/mc mb myminio/reports;
      /usr/bin/mc policy set download myminio/reports;
      exit 0;
      "
