server:
  port: 0
spring:
  application:
    name: worker-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5433/reports
    username: alex
    password: alex
    driver-class-name: org.postgresql.Driver

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.example.workerservice.serializers.ReportDeserializer
