server:
  port: 0

spring:
  application:
    name: master-service

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.example.masterservice.serializers.ReportSerializer
      transaction-id-prefix: tx-master-
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.example.masterservice.serializers.ReportDeserializer
      enable-auto-commit: false
      properties:
        isolation_level: read_committed
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://eureka:2000/eureka
logging:
  level:
    org.springframework.transaction: trace
    org.springframework.kafka.transaction: debug
    org.springframework.jdbc: debug