server:
  port: 0

spring:
  application:
    name: master-service

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.example.masterservice.serializers.ReportSerializer
