server:
  port: 8080
spring:
  application:
    name: client-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/clients
    username: alex
    password: alex
    driver-class-name: org.postgresql.Driver